apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app throttled
  labels:
    app: *app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *app
  strategy: {}
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
        - image: quay.io/alexeldeib/throttled:latest
          imagePullPolicy: Always
          command: ["/throttled"]
          name: *app
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 250m
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 50m
          volumeMounts:
            - name: azure
              mountPath: "/etc/kubernetes"
              readOnly: true
            - name: disk
              mountPath: "/dev/disk/azure/scsi1"
              readOnly: true
      volumes:
        - name: azure
          hostPath:
            path: "/etc/kubernetes"
        - name: disk
          hostPath:
            path: "/dev/disk/azure/scsi1"
